# -*- coding: utf-8 -*-
"""A SYNTHETIC duct drawing for the DWG -> MEP network route - generated, never copied from a project.

    python make_mep_dwg.py <out_folder> [--engine <accoreconsole.exe>] [--template <acad.dwt>]

Writes <out_folder>/MEP-DUCT.dwg and MEP-DUCT.truth.json. Refuses to overwrite. Inches (INSUNITS 1),
single-line centrelines, which is how a physical plan draws a main:

    M-SUPPLY   LINE      (0,0)-(160,0)                    the main, first length
               LWPOLYLINE (160,0)-(320,0)-(320,200)        the main continues and turns: one polyline, so a
                                                           run drawn as a polyline piece is exercised
               LINE      (160,0)-(160,-120)               a branch; the main is BROKEN at (160,0), which is
                                                           how a drawing says "tee" rather than "crossing"
    M-EXHAUST  LINE      (240,-80)-(240,120)              another system passing the supply main at
                                                           (240,0) - it must NOT be joined to it

The truth file declares what a correct route reads and builds; heights, sizes and systems are TEST
values of the spec that uses this drawing, not facts of the drawing.
"""
import hashlib
import io
import json
import os
import subprocess
import sys

ENGINE = r'C:\Program Files\Autodesk\AutoCAD 2025\accoreconsole.exe'
TEMPLATE = r'C:\Program Files\Autodesk\AutoCAD 2025\UserDataCache\en-US\Template\acad.dwt'

LINES = [('M-SUPPLY', (0, 0), (160, 0)), ('M-SUPPLY', (160, 0), (160, -120)), ('M-EXHAUST', (240, -80), (240, 120))]
POLYLINES = [('M-SUPPLY', [(160, 0), (320, 0), (320, 200)])]
TRUTH = {
    'runs': 5,
    'junctions': {'tee_at_in': [160, 0], 'elbow_at_in': [320, 0]},
    'terminals_in': [[0, 0], [160, -120], [320, 200], [240, -80], [240, 120]],
    'crossing_not_connected_at_in': [240, 0],
    'after_connect': {'supply_component': {'ducts': 4, 'fittings': 2, 'open_connectors': 3},
                      'exhaust_component': {'ducts': 1, 'fittings': 0, 'open_connectors': 2},
                      'components': 2},
}


def sha(p):
    h = hashlib.sha256()
    with open(p, 'rb') as f:
        for b in iter(lambda: f.read(1 << 20), b''):
            h.update(b)
    return h.hexdigest()


def layer(name, colour):
    return ('(entmake (list (cons 0 "LAYER") (cons 100 "AcDbSymbolTableRecord") (cons 100 "AcDbLayerTableRecord") '
            '(cons 2 "%s") (cons 70 0) (cons 62 %d)))' % (name, colour))


def main(folder, engine=ENGINE, template=TEMPLATE):
    os.makedirs(folder, exist_ok=True)
    dwg = os.path.join(folder, 'MEP-DUCT.dwg')
    if os.path.exists(dwg):
        raise SystemExit('%s exists; it is never overwritten' % dwg)
    body = ['(setvar "FILEDIA" 0)', '(setvar "CMDDIA" 0)', '(setvar "INSUNITS" 1)', layer('M-SUPPLY', 4), layer('M-EXHAUST', 6)]
    for lay, a, b in LINES:
        body.append('(entmake (list (cons 0 "LINE") (cons 8 "%s") (list 10 %s %s 0.0) (list 11 %s %s 0.0)))'
                    % (lay, float(a[0]), float(a[1]), float(b[0]), float(b[1])))
    for lay, pts in POLYLINES:
        verts = ' '.join('(list 10 %s %s)' % (float(x), float(y)) for x, y in pts)
        body.append('(entmake (list (cons 0 "LWPOLYLINE") (cons 100 "AcDbEntity") (cons 8 "%s") '
                    '(cons 100 "AcDbPolyline") (cons 90 %d) (cons 70 0) %s))' % (lay, len(pts), verts))
    body.append('(command "_.SAVEAS" "2018" "%s")' % dwg.replace('\\', '/'))
    scr = os.path.join(folder, 'MEP-DUCT.scr')
    io.open(scr, 'w', encoding='utf-8', newline='\r\n').write('\n'.join(body) + '\n')
    r = subprocess.run([engine, '/i', template, '/s', scr, '/l', 'en-US'], capture_output=True, timeout=600)
    io.open(os.path.join(folder, 'MEP-DUCT.log'), 'wb').write(r.stdout + r.stderr)
    if not os.path.exists(dwg):
        raise SystemExit('the console produced no MEP-DUCT.dwg; see its log')
    out = {'units': 'inch', 'note': 'generated by make_mep_dwg.py; a test drawing, not a project',
           'lines_in': LINES, 'polylines_in': POLYLINES, 'truth': TRUTH,
           'drawing': {'file': 'MEP-DUCT.dwg', 'sha256': sha(dwg)}}
    io.open(os.path.join(folder, 'MEP-DUCT.truth.json'), 'w', encoding='utf-8').write(json.dumps(out, indent=1))
    print(json.dumps(out['drawing']))


if __name__ == '__main__':
    args = sys.argv[1:]
    opts = {}
    while len(args) > 1 and args[-2].startswith('--'):
        opts[args[-2][2:]] = args[-1]
        args = args[:-2]
    main(args[0], opts.get('engine', ENGINE), opts.get('template', TEMPLATE))
