# -*- coding: utf-8 -*-
"""Two SYNTHETIC drawings for a wall SPLIT with openings on it - generated, never copied from a project.

    python make_split_dwgs.py <out_folder> [--engine <accoreconsole.exe>] [--template <acad.dwt>]

Writes <out_folder>/SPLIT-A.dwg (the wall whole), SPLIT-B.dwg (the revision: the same wall with a gap)
and SPLIT.truth.json. Refuses to overwrite. Inches, layer A-WALL, one 8 in wall drawn as face lines:

    A:  x 0..240, y 0..8
    B:  x 0..70 and x 130..240 (a 60 in gap); the 110 in piece is the longest and carries more openings,
        so it keeps the wall's id

The openings are NOT in the drawings: split_openings.py places them in the model (a door or window is
the model's, not the electrical drawing's), from this same truth file:

    D-KEEP  door    x 160   on the piece that keeps the id    -> stays, same id, same place
    W-KEEP  window  x 215   on the piece that keeps the id    -> stays, same id, same place
    D-OFF   door    x 35    on the NEW piece                  -> "stay" is impossible (an opening is not
                                                                 moved or re-created); decided delete
    W-GAP   window  x 100   in the removed stretch            -> decided delete
"""
import hashlib
import io
import json
import os
import subprocess
import sys

ENGINE = r'C:\Program Files\Autodesk\AutoCAD 2025\accoreconsole.exe'
TEMPLATE = r'C:\Program Files\Autodesk\AutoCAD 2025\UserDataCache\en-US\Template\acad.dwt'

DRAWINGS = {
    'SPLIT-A': [((0, 0), (240, 0)), ((0, 8), (240, 8)), ((0, 0), (0, 8)), ((240, 0), (240, 8))],
    'SPLIT-B': [((0, 0), (70, 0)), ((0, 8), (70, 8)), ((0, 0), (0, 8)), ((70, 0), (70, 8)),
                ((130, 0), (240, 0)), ((130, 8), (240, 8)), ((130, 0), (130, 8)), ((240, 0), (240, 8))],
}
OPENINGS = [
    {'id': 'D-KEEP', 'kind': 'door', 'x_in': 160, 'expect': 'stays'},
    {'id': 'W-KEEP', 'kind': 'window', 'x_in': 215, 'expect': 'stays'},
    {'id': 'D-OFF', 'kind': 'door', 'x_in': 35, 'expect': 'stay_refused_then_deleted'},
    {'id': 'W-GAP', 'kind': 'window', 'x_in': 100, 'expect': 'deleted'},
]


def sha(p):
    h = hashlib.sha256()
    with open(p, 'rb') as f:
        for b in iter(lambda: f.read(1 << 20), b''):
            h.update(b)
    return h.hexdigest()


def draw(folder, name, lines, engine, template):
    dwg = os.path.join(folder, name + '.dwg')
    if os.path.exists(dwg):
        raise SystemExit('%s exists; it is never overwritten' % dwg)
    body = ['(setvar "FILEDIA" 0)', '(setvar "CMDDIA" 0)', '(setvar "INSUNITS" 1)',
            '(entmake (list (cons 0 "LAYER") (cons 100 "AcDbSymbolTableRecord") (cons 100 "AcDbLayerTableRecord") '
            '(cons 2 "A-WALL") (cons 70 0) (cons 62 1)))']
    for (a, b) in lines:
        body.append('(entmake (list (cons 0 "LINE") (cons 8 "A-WALL") (list 10 %s %s 0.0) (list 11 %s %s 0.0)))'
                    % (float(a[0]), float(a[1]), float(b[0]), float(b[1])))
    body.append('(command "_.SAVEAS" "2018" "%s")' % dwg.replace('\\', '/'))
    scr = os.path.join(folder, name + '.scr')
    io.open(scr, 'w', encoding='utf-8', newline='\r\n').write('\n'.join(body) + '\n')
    r = subprocess.run([engine, '/i', template, '/s', scr, '/l', 'en-US'], capture_output=True, timeout=600)
    io.open(os.path.join(folder, name + '.log'), 'wb').write(r.stdout + r.stderr)
    if not os.path.exists(dwg):
        raise SystemExit('the console produced no %s; see its log' % name)
    return dwg


def main(folder, engine=ENGINE, template=TEMPLATE):
    os.makedirs(folder, exist_ok=True)
    out = {'units': 'inch', 'note': 'generated by make_split_dwgs.py; a test drawing pair, not a project',
           'wall': {'thickness_in': 8, 'centre_y_in': 4}, 'openings': OPENINGS,
           'pieces_in_B': {'new': [0, 70], 'kept': [130, 240]}, 'drawings': {}}
    for name, lines in DRAWINGS.items():
        dwg = draw(folder, name, lines, engine, template)
        out['drawings'][name] = {'file': os.path.basename(dwg), 'sha256': sha(dwg), 'lines_in': lines}
    io.open(os.path.join(folder, 'SPLIT.truth.json'), 'w', encoding='utf-8').write(json.dumps(out, indent=1))
    print(json.dumps({k: v['sha256'] for k, v in out['drawings'].items()}, indent=1))


if __name__ == '__main__':
    args = sys.argv[1:]
    opts = {}
    while len(args) > 1 and args[-2].startswith('--'):
        opts[args[-2][2:]] = args[-1]
        args = args[:-2]
    main(args[0], opts.get('engine', ENGINE), opts.get('template', TEMPLATE))
