/// Coordination findings exported by horizun_coordination operation=export format=csv (one row per clash pair).
table Findings
	lineageTag: 25ec4d3b-a1de-4f9f-93f3-6d04144b74f6

	measure 'Open Critical or High' = CALCULATE ( [Open Findings], Findings[priority] IN { "critical", "high" } )
		formatString: #,0
		displayFolder: Coordination
		lineageTag: 384507ba-cac5-499f-b010-30c0c5dd7d50

	measure 'Resolution Rate' = DIVIDE ( [Resolved by Model], [Findings Total] )
		formatString: 0.0%
		displayFolder: Coordination
		lineageTag: 9e083b45-4eb2-46e0-a2a3-66a5de6e6b19

	/// Pairs that came back after being resolved.
	measure Regressions = CALCULATE ( COUNTROWS ( Findings ), Findings[regression] = TRUE () )
		formatString: #,0
		displayFolder: Coordination
		lineageTag: c13ad0ed-45cb-4e5e-bddd-9c58deb97d5f

	/// Pairs a person accepted or closed; they are still in the model.
	measure 'Closed by Decision' = CALCULATE ( COUNTROWS ( Findings ), Findings[status] IN { "accepted_risk", "closed_by_decision" } )
		formatString: #,0
		displayFolder: Coordination
		lineageTag: dd390966-9938-488e-b987-3b7a4a53c5b0

	/// Pairs a complete detection run measured as gone - never set by hand.
	measure 'Resolved by Model' = CALCULATE ( COUNTROWS ( Findings ), Findings[status] = "resolved_by_model" )
		formatString: #,0
		displayFolder: Coordination
		lineageTag: 18b51c52-5171-4820-b1fc-7fd63eb0e029

	/// Clash pairs still in the model: status open or assigned.
	measure 'Open Findings' = CALCULATE ( COUNTROWS ( Findings ), Findings[status] IN { "open", "assigned" } )
		formatString: #,0
		displayFolder: Coordination
		lineageTag: c7dd1111-2bfc-48ff-b6ef-d54b90987781

	measure 'Findings Total' = COUNTROWS ( Findings )
		formatString: #,0
		displayFolder: Coordination
		lineageTag: d3bdb371-a096-499d-bee5-5082143895cf

	column finding_id
		dataType: string
		lineageTag: 2369a1cc-5b12-4abe-bb9e-22637b388b43
		summarizeBy: none
		sourceColumn: finding_id

	column status
		dataType: string
		lineageTag: d6d91cee-0dc9-4ce7-8310-029b2cfd1091
		summarizeBy: none
		sourceColumn: status

	column assignee
		dataType: string
		lineageTag: 5b57df9d-7e7a-4e18-9b7c-7e428ec14c2f
		summarizeBy: none
		sourceColumn: assignee

	column note
		dataType: string
		lineageTag: 39ed490f-1685-4446-affb-3cfcdaa54f44
		summarizeBy: none
		sourceColumn: note

	column category_a
		dataType: string
		lineageTag: 2d979177-80a6-4266-b32a-d082ec575b3a
		summarizeBy: none
		sourceColumn: category_a

	column category_b
		dataType: string
		lineageTag: 6f3d0dea-24ef-4da1-b6c7-9fc4301f9bbb
		summarizeBy: none
		sourceColumn: category_b

	column side_a
		dataType: string
		lineageTag: 44c38ade-ecb3-4c62-ba1c-5cb9897283c8
		summarizeBy: none
		sourceColumn: side_a

	column side_b
		dataType: string
		lineageTag: 435ef3e2-8bd7-4815-abdc-6648abf02c0a
		summarizeBy: none
		sourceColumn: side_b

	column point_mm
		dataType: string
		lineageTag: 315afbe1-3cb0-4f5f-9d4d-f5fcfeafa34f
		summarizeBy: none
		sourceColumn: point_mm

	column first_seen_utc
		dataType: dateTime
		formatString: Short Date
		lineageTag: 62f5c6db-c53c-4dfd-86e1-9211bfc488eb
		summarizeBy: none
		sourceColumn: first_seen_utc

	column last_seen_utc
		dataType: dateTime
		formatString: Short Date
		lineageTag: 64344808-8248-4fb0-b9b7-7fb489923daf
		summarizeBy: none
		sourceColumn: last_seen_utc

	column resolved_utc
		dataType: dateTime
		formatString: Short Date
		lineageTag: 72468047-3dcb-4645-8000-80ac8fe2bd15
		summarizeBy: none
		sourceColumn: resolved_utc

	column times_seen
		dataType: int64
		formatString: 0
		lineageTag: eefbbdbc-0963-4931-8497-e75641cd06ba
		summarizeBy: sum
		sourceColumn: times_seen

	column regression
		dataType: boolean
		lineageTag: 329e0013-8b1b-43c8-bbe6-c793c1fe0f86
		summarizeBy: none
		sourceColumn: regression

	column scope
		dataType: string
		lineageTag: 55df146d-ada9-41e6-a988-f301cf21ab44
		summarizeBy: none
		sourceColumn: scope

	column external_source
		dataType: string
		lineageTag: 9e178f5a-d25c-4c92-83b1-ba215baede80
		summarizeBy: none
		sourceColumn: external_source

	column external_issue_id
		dataType: string
		lineageTag: 3e9ffbe3-9267-42db-b717-a6bd53abf873
		summarizeBy: none
		sourceColumn: external_issue_id

	column priority
		dataType: string
		lineageTag: 2e60115d-bea3-40a0-aed4-bf0d70e62dc7
		summarizeBy: none
		sourceColumn: priority

	column responsible
		dataType: string
		lineageTag: da77a7cb-0622-44d5-a958-5019c4212888
		summarizeBy: none
		sourceColumn: responsible

	column immovable_discipline
		dataType: string
		lineageTag: 17eca3e0-a3f7-4c7c-b71e-bbce92e5732d
		summarizeBy: none
		sourceColumn: immovable_discipline

	partition Findings = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(LedgerCsvPath), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"finding_id", type text}, {"status", type text}, {"assignee", type text}, {"note", type text}, {"category_a", type text}, {"category_b", type text}, {"side_a", type text}, {"side_b", type text}, {"point_mm", type text}, {"first_seen_utc", type datetimezone}, {"last_seen_utc", type datetimezone}, {"resolved_utc", type datetimezone}, {"times_seen", Int64.Type}, {"regression", type logical}, {"scope", type text}, {"external_source", type text}, {"external_issue_id", type text}, {"priority", type text}, {"responsible", type text}, {"immovable_discipline", type text}}, "en-US"),
				    #"Source Label" = Table.ReplaceValue(#"Changed Type", "", "horizun_clash", Replacer.ReplaceValue, {"external_source"})
				in
				    #"Source Label"

	annotation PBI_ResultType = Table
