#Requires -Version 5.1
<#
  THE DIAGNOSTICS PROGRAMME'S LEDGER, GENERATED.

  docs/MODEL-DIAGNOSTICS-PROGRAM-STATE.json is written by this script from files
  something else produced: the backlog JSON, the benchmark source inventory,
  docs/inventory.json which the built server produced, and - when one exists -
  the live roll-up the diagnostics suite wrote.

  A row that says null says so because nothing measured it, never because it was
  assumed to work. The structural ledger learned that the hard way: it carried
  `multiversion: null` with a sentence asserting no other Revit had been opened,
  and went on carrying it after five had been measured. Nothing in this file is
  typed by hand for the same reason.

  Usage:
    pwsh -File scripts/generate-diagnostics-state.ps1
    pwsh -File scripts/generate-diagnostics-state.ps1 -SkipTests
#>
[CmdletBinding()]
param([string]$Out, [switch]$SkipTests)
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repo = Split-Path -Parent $PSScriptRoot
if (-not $Out) { $Out = Join-Path $repo 'docs\MODEL-DIAGNOSTICS-PROGRAM-STATE.json' }

function Read-Json([string]$Path) {
    if (-not (Test-Path -LiteralPath $Path)) { return $null }
    Get-Content -LiteralPath $Path -Raw | ConvertFrom-Json
}
function Sha([string]$Path) {
    if (-not (Test-Path -LiteralPath $Path)) { return $null }
    (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()
}

$backlogPath = Join-Path $repo 'docs\evidence\model-diagnostics-backlog.json'
$sourcesPath = Join-Path $repo 'docs\evidence\model-diagnostics-sources.json'
$inventoryPath = Join-Path $repo 'docs\inventory.json'
$backlog = Read-Json $backlogPath
$sources = Read-Json $sourcesPath
$inventory = Read-Json $inventoryPath

# A ROLL-UP IF THERE IS ONE, THE HARNESS ARTIFACT IF THERE IS NOT, and the ledger
# says which it read. There is one diagnostics harness, so a roll-up over it would
# be a file with one row; when a second lands, verify-diagnostics-all.ps1 becomes
# worth writing and this prefers it automatically.
$artifactDir = Join-Path $repo 'artifacts\live'
$rollUp = $null
$rollUpName = $null
$rollUpKind = $null
if (Test-Path -LiteralPath $artifactDir) {
    foreach ($pattern in @('diagnostics-all-*.json', 'diagnostics-*.json')) {
        $found = @(Get-ChildItem -LiteralPath $artifactDir -Filter $pattern -ErrorAction SilentlyContinue |
                   Where-Object { $pattern -eq 'diagnostics-all-*.json' -or $_.Name -notlike 'diagnostics-all-*' } |
                   Sort-Object LastWriteTime -Descending)
        if ($found.Count -eq 0) { continue }
        $rollUp = Get-Content -LiteralPath $found[0].FullName -Raw | ConvertFrom-Json
        $rollUpName = $found[0].Name
        $rollUpKind = $(if ($pattern -eq 'diagnostics-all-*.json') { 'roll_up' } else { 'single_harness' })
        break
    }
}

$core = [ordered]@{ passed = $null; failed = $null }
$server = [ordered]@{ passed = $null; failed = $null }
if (-not $SkipTests) {
    Write-Host '[diagnostics-state] measuring the offline suites...' -ForegroundColor DarkGray
    foreach ($pair in @(@{ p = 'tests\Horizun.Core.Tests'; t = $core }, @{ p = 'tests\Horizun.Server.Tests'; t = $server })) {
        # NOT $out. PowerShell variables are CASE-INSENSITIVE, so `$out` and the
        # `$Out` destination-path parameter are the SAME variable: assigning the
        # test log here overwrote the path, and the script then died at the final
        # Set-Content with "A parameter cannot be found that matches parameter
        # name 'Encoding'" - an error that names neither the variable nor the
        # line that broke it. It only ever failed WITHOUT -SkipTests, which is
        # why it survived: the fast path never runs this loop.
        $runOutput = & dotnet test (Join-Path $repo $pair.p) -c Release --nologo 2>&1 | Out-String
        if ($runOutput -match 'Failed:\s+(\d+),\s+Passed:\s+(\d+)') {
            $pair.t.failed = [int]$Matches[1]
            $pair.t.passed = [int]$Matches[2]
        }
    }
}

$head = (& git -C $repo rev-parse HEAD).Trim()
$dirty = @(& git -C $repo status --porcelain --untracked-files=no)

# THE BACKLOG, COUNTED HERE rather than copied from its own summary.
$stories = @($backlog.stories)
$bySize = @{}
$byPriority = @{}
foreach ($s in $stories) {
    if (-not $bySize.ContainsKey([string]$s.size)) { $bySize[[string]$s.size] = 0 }
    $bySize[[string]$s.size]++
    if (-not $byPriority.ContainsKey([string]$s.priority)) { $byPriority[[string]$s.priority] = 0 }
    $byPriority[[string]$s.priority]++
}
$enabling = @($stories | Where-Object { $_.number -is [string] })
$done = @($stories | Where-Object {
    $_.PSObject.Properties.Name -contains 'status' -and [string]$_.status -eq 'done' })

$state = [ordered]@{
    schema = 'horizun.diagnostics-program/1'
    what_this_is =
        'The Native Revit Model Diagnostics programme''s ledger, GENERATED by ' +
        'scripts/generate-diagnostics-state.ps1 from files something else wrote. A row that says null says so ' +
        'because nothing measured it, never because it was assumed to work.'
    generated_utc = (Get-Date).ToUniversalTime().ToString('o')
    generated_by = 'scripts/generate-diagnostics-state.ps1'
    generated_from = [ordered]@{
        backlog = 'docs/evidence/model-diagnostics-backlog.json'
        backlog_sha256 = Sha $backlogPath
        benchmark_sources = 'docs/evidence/model-diagnostics-sources.json'
        benchmark_sources_sha256 = Sha $sourcesPath
        inventory = 'docs/inventory.json'
        live_roll_up = $rollUpName
    }
    repo = [ordered]@{
        head = $head
        tracked_clean_at_generation = ($dirty.Count -eq 0)
        modified_at_generation = @($dirty)
        means =
            'the tree when this generator started. It says nothing about any live number below - those belong ' +
            'to an installed binary measured earlier - only whether this ledger was generated from a state ' +
            'somebody else could reproduce.'
    }
    benchmark = $(if ($sources) { [ordered]@{
        swept_utc = $sources.swept_utc
        products = @($sources.products).Count
        sources = @($sources.products | ForEach-Object { $_.sources }).Count
        claims = @($sources.products | ForEach-Object { $_.claims }).Count
        unknowns_with_what_was_searched = @($sources.products | ForEach-Object { $_.unknowns }).Count
        contradictions_printed_not_resolved = @($sources.products | ForEach-Object { $_.contradictions }).Count
        measured_claims = @($sources.products | ForEach-Object { $_.claims } |
                            Where-Object { $_.label -eq 'MEASURED' }).Count
        measured_claims_means =
            'every one of them comes from a single third-party review of a product that has since been ' +
            'renamed. No vendor in the set publishes a reproducible measurement of anything.'
    } } else { $null })
    backlog = $(if ($backlog) { [ordered]@{
        stories = $stories.Count
        enabling = $enabling.Count
        enabling_means =
            'prerequisites an adversarial pass proved, each verified against the working tree: the gate cannot ' +
            'express a list requirement or two counts from one finding, audit_model is never told which ' +
            'document it is auditing, and model_scan has one global cap nine stories would compete for.'
        by_priority = $byPriority
        by_size = $bySize
        done = $done.Count
        partial = @($stories | Where-Object {
            $_.PSObject.Properties.Name -contains 'status' -and [string]$_.status -eq 'partial' }).Count
        partial_means =
            'the decision half is built and tested Revit-free, and something it needs is not: a model_scan ' +
            'section, a stored snapshot, or a feed from a live audit. Named per story in the backlog.'
        done_means =
            'a story is done when its acceptance criteria are observably met - a Core test, a live probe, and ' +
            'the artifact that proves it. Zero here means the backlog is written and the work is not.'
    } } else { $null })
    static = [ordered]@{
        core_tests = $core
        server_tests = $server
        measured = $(if ($SkipTests) { 'skipped by -SkipTests' } else { 'here, this run' })
    }
    live = $(if ($rollUp) { [ordered]@{
        read_from = $rollUpKind
        artifact = $rollUpName
        revit_year = $rollUp.revit_year
        revit_build = $rollUp.revit_build
        candidate = $(if ($rollUpKind -eq 'roll_up') { $rollUp.candidate } else { $rollUp.code_candidate_commit })
        built_from_clean_tree = $(if ($rollUpKind -eq 'roll_up') { $rollUp.built_from_clean_tree } else { $null })
        harnesses = $(if ($rollUpKind -eq 'roll_up') { $rollUp.steps_run } else { 1 })
        harnesses_failed = $(if ($rollUpKind -eq 'roll_up') { $rollUp.steps_failed } else { $(if ([int]$rollUp.failed -gt 0) { 1 } else { 0 }) })
        totals = $(if ($rollUpKind -eq 'roll_up') { $rollUp.totals } else { [ordered]@{
            passed = [int]$rollUp.passed; failed = [int]$rollUp.failed
            unverified = [int]$rollUp.unverified; not_covered = [int]$rollUp.not_covered
            fixture_missing = [int]$rollUp.fixture_missing } })
    } } else { $null })
    live_means =
        $(if ($rollUp) {
            'read from ' + $rollUpName +
            $(if ($rollUpKind -eq 'single_harness') {
                ' - the one diagnostics harness, not a roll-up. A roll-up over a single harness would be a ' +
                'file with one row; when a second harness lands, verify-diagnostics-all.ps1 becomes worth ' +
                'writing and this generator prefers it automatically.' } else { '.' }) }
          else {
            'null because no diagnostics live roll-up exists yet - scripts/live/verify-diagnostics-all.ps1 has ' +
            'not been written or has not been run. This is a statement about the evidence, not about the code.'
          })
    inventory = $(if ($inventory) { [ordered]@{
        tools = $inventory.counts.tools
        operations = $inventory.counts.operations
        enumerated_variants = $inventory.counts.enumerated_variants
        contract_hash = $inventory.generated_from_contract_hash
    } } else { $null })
    out_of_scope = @(
        'IFC and COBie. This programme is about the native model; a finding that survives a round trip through ' +
        'an export schema is a finding about the schema.',
        'Any organisation''s standards compiled in. Where a check needs a threshold, a naming grammar or a ' +
        'parameter list, it arrives as an argument.',
        'Telemetry. Nothing here sends anything off the machine.'
    )
}

$state | ConvertTo-Json -Depth 20 | Set-Content -LiteralPath $Out -Encoding UTF8
Write-Host ("[diagnostics-state] {0} stories ({1} enabling), {2} done; benchmark {3} sources / {4} claims" -f
    $stories.Count, $enabling.Count, $done.Count,
    $(if ($sources) { @($sources.products | ForEach-Object { $_.sources }).Count } else { 0 }),
    $(if ($sources) { @($sources.products | ForEach-Object { $_.claims }).Count } else { 0 }))
Write-Host ("[diagnostics-state] written to " + $Out)
