#Requires -Version 5.1
<#
  THE DIAGNOSTICS BACKLOG, GENERATED.

  docs/MODEL-DIAGNOSTICS-BACKLOG.md is written from
  docs/evidence/model-diagnostics-backlog.json so that the eleven fields every
  story must carry - current state, existing evidence, gap, contract, core test,
  live test, acceptance, risks, dependencies, size, priority - cannot quietly
  become ten in one story and nine in another.

  The current_state field is the one that matters. A backlog whose stories begin
  "nothing exists" is a backlog that sends people to build things that are
  already built, which is precisely the error the benchmark made about this
  bridge before eight readings of src/ corrected it.

  Usage:
    pwsh -File scripts/generate-diagnostics-backlog.ps1
#>
[CmdletBinding()]
param([string]$Source, [string]$Out)
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repo = Split-Path -Parent $PSScriptRoot
if (-not $Source) { $Source = Join-Path $repo 'docs\evidence\model-diagnostics-backlog.json' }
if (-not $Out) { $Out = Join-Path $repo 'docs\MODEL-DIAGNOSTICS-BACKLOG.md' }
if (-not (Test-Path -LiteralPath $Source)) { throw "backlog source not found: $Source" }

$d = Get-Content -LiteralPath $Source -Raw | ConvertFrom-Json
$sha = (Get-FileHash -LiteralPath $Source -Algorithm SHA256).Hash.ToLowerInvariant()
$stories = @($d.stories)

# EVERY STORY CARRIES EVERY FIELD, or this refuses. A backlog with a hole in it
# is worse than a shorter backlog, because the hole is invisible in a summary.
# A PROSE FIELD MUST SAY SOMETHING; A LIST MAY BE EMPTY BUT MUST EXIST. An empty
# dependencies array is a story with no dependencies, which is a fact. An absent
# one is a story where nobody asked, which is a hole. Conflating the two made
# this gate refuse nine perfectly complete stories on its first run.
$requiredProse = @('number', 'title', 'current_state', 'gap', 'contract', 'core_test', 'live_test',
                   'size', 'priority', 'status')
$requiredLists = @('acceptance', 'risks', 'dependencies')
$mustNotBeEmpty = @('acceptance')
# A CLOSED VOCABULARY. done and implemented_not_live_verified are DIFFERENT
# claims and the difference is the whole point: one has been measured against a
# real Revit and the other has not. A status outside this list is a word
# somebody invented, and a reader cannot tell an invented one from a real one.
$knownStatuses = @('done', 'implemented_not_live_verified', 'partial', 'not_started')
$holes = @()
foreach ($s in $stories) {
    if (($s.PSObject.Properties.Name -contains 'status') -and $s.status -and
        $knownStatuses -notcontains [string]$s.status) {
        $holes += ("story " + $s.number + " has status '" + $s.status + "', which is not one of: " +
                   ($knownStatuses -join ', '))
    }
    foreach ($f in $requiredProse) {
        $has = $s.PSObject.Properties.Name -contains $f
        if (-not $has -or $null -eq $s.$f -or ([string]$s.$f).Trim().Length -eq 0) {
            $holes += ("story " + $s.number + " is missing '" + $f + "'")
        }
    }
    foreach ($f in $requiredLists) {
        if (-not ($s.PSObject.Properties.Name -contains $f)) {
            $holes += ("story " + $s.number + " never answered '" + $f + "' - absent is not the same as empty")
            continue
        }
        if ($mustNotBeEmpty -contains $f -and @($s.$f).Count -eq 0) {
            $holes += ("story " + $s.number + " has no " + $f + ", so nothing could show it was done")
        }
    }
}
if ($holes.Count -gt 0) { throw ("incomplete stories:`n  " + ($holes -join "`n  ")) }

$sb = New-Object System.Text.StringBuilder
function W([string]$l) { $null = $sb.AppendLine($l) }
function Esc([string]$s) { if ($null -eq $s) { '' } else { ($s -replace '\|', '\|') -replace '\r?\n', ' ' } }

W '# Native Revit Model Diagnostics — the backlog'
W ''
W '<!-- GENERATED by scripts/generate-diagnostics-backlog.ps1 from'
W '     docs/evidence/model-diagnostics-backlog.json. Edit the JSON, not this file. -->'
W ''
W ('Generated ' + (Get-Date).ToUniversalTime().ToString('yyyy-MM-dd') +
  ' from `docs/evidence/model-diagnostics-backlog.json`, SHA-256 `' + $sha + '`.')
W ''
W ('**' + $d.counts.stories + ' stories** — ' + $d.counts.enabling + ' enabling and ' +
  ($d.counts.stories - $d.counts.enabling) + ' over the programme''s thirty topics. ' +
  $d.counts.p0 + ' P0, ' + $d.counts.p1 + ' P1, ' + $d.counts.p2 + ' P2.')
W ''
W ('> ' + (Esc $d.what_this_is))
W ''
W '## How this was written'
W ''
W (Esc $d.how_it_was_written)
W ''
W '**And where the critic was itself wrong:** ' + (Esc $d.the_critic_was_wrong_about)
W ''
W '---'
W ''
W '## The order'
W ''
W 'The three enabling stories come first because six, ten and nine of the others respectively cannot be built as'
W 'written until they land. Everything after that is ordered by priority, not by topic number.'
W ''
$tally = [ordered]@{}
foreach ($k in $knownStatuses) { $tally[$k] = @($stories | Where-Object { [string]$_.status -eq $k }).Count }
W ('**Where they stand.** ' + (($tally.Keys | ForEach-Object { '`' + $_ + '` ' + $tally[$_] }) -join ' · ') + '.')
W ''
W 'A story is `done` only when it has been measured against a running Revit. `implemented_not_live_verified`'
W 'means the code and its contract are in place and no Revit has confirmed it - a different claim, kept'
W 'separate on purpose, because collapsing the two is how a backlog comes to overstate what is proved.'
W ''
W '| # | Story | Status | Size | Priority | Depends on |'
W '|---|---|---|---|---|---|'
foreach ($s in $stories) {
    $dep = @(@($s.dependencies) | Where-Object { $_ })
    $depTxt = if ($dep.Count -gt 0) { ($dep -join ', ') } else { '—' }
    W ('| **' + $s.number + '** | ' + (Esc $s.title) + ' | `' + $s.status + '` | ' + $s.size + ' | ' +
       $s.priority + ' | ' + $depTxt + ' |')
}
W ''
W '---'
W ''

foreach ($s in $stories) {
    W ('## ' + $s.number + ' — ' + (Esc $s.title))
    W ''
    $dep = @(@($s.dependencies) | Where-Object { $_ })
    W ('`' + $s.status + '` · `' + $s.size + '` · `' + $s.priority + '`' +
       $(if ($dep.Count -gt 0) { ' · depends on ' + (($dep | ForEach-Object { '`' + $_ + '`' }) -join ', ') } else { '' }))
    if (($s.PSObject.Properties.Name -contains 'status_note') -and $s.status_note) {
        W ''
        W ('**Where it stands.** ' + (Esc $s.status_note))
    }
    W ''
    W '**What exists today.** ' + (Esc $s.current_state)
    W ''
    if ($s.PSObject.Properties.Name -contains 'existing_evidence' -and $s.existing_evidence) {
        W '**Evidence already standing.** ' + (Esc $s.existing_evidence)
        W ''
    }
    W '**The gap.** ' + (Esc $s.gap)
    W ''
    W '**Proposed contract.** ' + (Esc $s.contract)
    W ''
    W '**Core test (no Revit).** ' + (Esc $s.core_test)
    W ''
    W '**Live test.** ' + (Esc $s.live_test)
    W ''
    W '**Acceptance.**'
    W ''
    foreach ($a in @($s.acceptance)) { W ('- ' + (Esc $a)) }
    W ''
    $risks = @(@($s.risks) | Where-Object { $_ })
    if ($risks.Count -gt 0) {
        W '**Risks.**'
        W ''
        foreach ($r in $risks) { W ('- ' + (Esc $r)) }
        W ''
    }
    W '---'
    W ''
}

W '## The adversarial pass, in full'
W ''
W 'Kept because a backlog that discards its own critique is asking to be trusted twice.'
W ''
W '<details><summary>What the critic found</summary>'
W ''
W ([string]$d.critique)
W ''
W '</details>'
W ''

Set-Content -LiteralPath $Out -Value $sb.ToString() -Encoding UTF8
Write-Host ("[diagnostics-backlog] {0} stories ({1} enabling), {2} P0 / {3} P1 / {4} P2" -f
    $d.counts.stories, $d.counts.enabling, $d.counts.p0, $d.counts.p1, $d.counts.p2)
Write-Host ("[diagnostics-backlog] written to " + $Out)
